import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aaftab Pinjari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*to provide transitions to the page  we needed to use animation presence component of framer motion 
        it needs to use hooks so it need use client functionality*/}
        <TransitionProvider>
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
